version: "3.9"

networks:
    internal:

services:
  php:
    build:
     context: ./docker/php
     dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql
    ports:
      - "9001:9001"
    networks:
      - internal


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - internal

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    restart: unless-stopped
    command:
      --innodb_use_native_aio=0
      --authentication_policy=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
#      - MYSQL_USER=root
     - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_PASSWORD=root
#      - MYSQL_DATABASE=test
#      - MYSQL_PORT_3306_TCP_ADDR=mysql
#      - MYSQL_PORT_3306_TCP_PORT=3306
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
    restart: always
    ports:
      - "8081:80"
    networks:
      - internal
    links:
      - mysql
